insert into Concessionaria_T (Nazionalità, Città, Numero_Dipendenti, Numero_telefono) values ('BF', 'Koupla', 8, 5999596610);
insert into Concessionaria_T (Nazionalità, Città, Numero_Dipendenti, Numero_telefono) values ('CN', 'Yajiang', 2, 4127236176);
insert into Concessionaria_T (Nazionalità, Città, Numero_Dipendenti, Numero_telefono) values ('ID', 'Curahkalak Tengah', 2, 1452479600);
insert into Concessionaria_T (Nazionalità, Città, Numero_Dipendenti, Numero_telefono) values ('SI', 'Zgornje Pirnice', 4, 8945022233);
insert into Concessionaria_T (Nazionalità, Città, Numero_Dipendenti, Numero_telefono) values ('BY', 'Nyakhachava', 5, 8273861646);
insert into Concessionaria_T (Nazionalità, Città, Numero_Dipendenti, Numero_telefono) values ('ID', 'Mojokerto', 4, 1256128329);
insert into Concessionaria_T (Nazionalità, Città, Numero_Dipendenti, Numero_telefono) values ('BR', 'Ponte Nova', 2, 7489889933);
insert into Concessionaria_T (Nazionalità, Città, Numero_Dipendenti, Numero_telefono) values ('TH', 'Yasothon', 3, 6157344576);
insert into Concessionaria_T (Nazionalità, Città, Numero_Dipendenti, Numero_telefono) values ('CY', 'Kti', 5, 7593688114);
insert into Concessionaria_T (Nazionalità, Città, Numero_Dipendenti, Numero_telefono) values ('MX', 'Reforma', 3, 9524096138);
insert into Concessionaria_T (Nazionalità, Città, Numero_Dipendenti, Numero_telefono) values ('RU', 'Shumyachi', 1, 4273440769);
insert into Concessionaria_T (Nazionalità, Città, Numero_Dipendenti, Numero_telefono) values ('ID', 'Banjar Bongangede', 1, 2609063751);
insert into Concessionaria_T (Nazionalità, Città, Numero_Dipendenti, Numero_telefono) values ('CN', 'Rentian', 4, 9516851068);
insert into Concessionaria_T (Nazionalità, Città, Numero_Dipendenti, Numero_telefono) values ('ID', 'Lhoknga', 1, 5352130347);
insert into Concessionaria_T (Nazionalità, Città, Numero_Dipendenti, Numero_telefono) values ('CZ', 'Brasy', 3, 1995701094);
insert into Concessionaria_T (Nazionalità, Città, Numero_Dipendenti, Numero_telefono) values ('SE', 'Bors', 4, 5153429560);
insert into Concessionaria_T (Nazionalità, Città, Numero_Dipendenti, Numero_telefono) values ('MA', 'Taouloukoult', 2, 7535218391);
insert into Concessionaria_T (Nazionalità, Città, Numero_Dipendenti, Numero_telefono) values ('CN', 'Henanan', 2, 1119077882);
insert into Concessionaria_T (Nazionalità, Città, Numero_Dipendenti, Numero_telefono) values ('UA', 'Tomakivka', 2, 2713728181);
insert into Concessionaria_T (Nazionalità, Città, Numero_Dipendenti, Numero_telefono) values ('ID', 'Jumpangdua', 4, 3165273160);
insert into Concessionaria_T (Nazionalità, Città, Numero_Dipendenti, Numero_telefono) values ('CN', 'Houjia', 3, 8192811280);
insert into Concessionaria_T (Nazionalità, Città, Numero_Dipendenti, Numero_telefono) values ('RU', 'Pyatovskiy', 4, 6297580396);
insert into Concessionaria_T (Nazionalità, Città, Numero_Dipendenti, Numero_telefono) values ('JM', 'Black River', 6, 6274722288);
insert into Concessionaria_T (Nazionalità, Città, Numero_Dipendenti, Numero_telefono) values ('ID', 'Terangun', 6, 9634428053);
insert into Concessionaria_T (Nazionalità, Città, Numero_Dipendenti, Numero_telefono) values ('ID', 'Leubatang', 3, 6448605791);
insert into Concessionaria_T (Nazionalità, Città, Numero_Dipendenti, Numero_telefono) values ('PH', 'Busay', 6, 9843508502);
insert into Concessionaria_T (Nazionalità, Città, Numero_Dipendenti, Numero_telefono) values ('KZ', 'Shardara', 2, 8876343985);
insert into Concessionaria_T (Nazionalità, Città, Numero_Dipendenti, Numero_telefono) values ('GE', 'Kelasuri', 3, 8519378884);
insert into Concessionaria_T (Nazionalità, Città, Numero_Dipendenti, Numero_telefono) values ('SE', 'Floda', 5, 1546158646);
insert into Concessionaria_T (Nazionalità, Città, Numero_Dipendenti, Numero_telefono) values ('CM', 'Fundong', 4, 2939781322);
insert into Concessionaria_T (Nazionalità, Città, Numero_Dipendenti, Numero_telefono) values ('PL', 'Rozwadza', 6, 5535775982);
insert into Concessionaria_T (Nazionalità, Città, Numero_Dipendenti, Numero_telefono) values ('NG', 'Riti', 3, 9426034902);
insert into Concessionaria_T (Nazionalità, Città, Numero_Dipendenti, Numero_telefono) values ('EG', 'Al Fashn', 2, 9945038690);
insert into Concessionaria_T (Nazionalità, Città, Numero_Dipendenti, Numero_telefono) values ('CN', 'Guxi', 7, 4862598300);
insert into Concessionaria_T (Nazionalità, Città, Numero_Dipendenti, Numero_telefono) values ('CN', 'Donglai', 5, 3704653525);
insert into Concessionaria_T (Nazionalità, Città, Numero_Dipendenti, Numero_telefono) values ('CN', 'Dengzhou', 4, 3106500998);
insert into Concessionaria_T (Nazionalità, Città, Numero_Dipendenti, Numero_telefono) values ('SE', 'Tyres', 3, 5556958034);
insert into Concessionaria_T (Nazionalità, Città, Numero_Dipendenti, Numero_telefono) values ('CN', 'Xinzhou', 6, 7225648586);
insert into Concessionaria_T (Nazionalità, Città, Numero_Dipendenti, Numero_telefono) values ('FI', 'Savitaipale', 4, 4818176503);
insert into Concessionaria_T (Nazionalità, Città, Numero_Dipendenti, Numero_telefono) values ('FR', 'Creil', 6, 5368926844);
insert into Concessionaria_T (Nazionalità, Città, Numero_Dipendenti, Numero_telefono) values ('ID', 'Ambarawa', 5, 4557941255);
insert into Concessionaria_T (Nazionalità, Città, Numero_Dipendenti, Numero_telefono) values ('UA', 'Chortkiv', 3, 9026605033);
insert into Concessionaria_T (Nazionalità, Città, Numero_Dipendenti, Numero_telefono) values ('BR', 'Montes Claros', 2, 3443791125);
insert into Concessionaria_T (Nazionalità, Città, Numero_Dipendenti, Numero_telefono) values ('CN', 'Zhongxing', 6, 1024031296);
insert into Concessionaria_T (Nazionalità, Città, Numero_Dipendenti, Numero_telefono) values ('IR', 'Sardasht', 5, 8762525272);
insert into Concessionaria_T (Nazionalità, Città, Numero_Dipendenti, Numero_telefono) values ('PH', 'San Miguel', 4, 8614102026);
insert into Concessionaria_T (Nazionalità, Città, Numero_Dipendenti, Numero_telefono) values ('CN', 'Hengjie', 2, 4431306576);
insert into Concessionaria_T (Nazionalità, Città, Numero_Dipendenti, Numero_telefono) values ('RU', 'Yashalta', 3, 1979059575);
insert into Concessionaria_T (Nazionalità, Città, Numero_Dipendenti, Numero_telefono) values ('PL', 'Niedzwiedz', 1, 3848702243);
insert into Concessionaria_T (Nazionalità, Città, Numero_Dipendenti, Numero_telefono) values ('ID', 'Kapinango', 4, 1767427719);
