INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('ACFGNQ30L49C290E','VUE');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('ATOPPV18I18V056E','TT');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('AVJMVS27Z20H763L','Avenger');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('AYYGFF86S30M223A','Accent');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('BGQMOS11P86Q149K','C8 Spyder');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('BTLCNU38B77A480P','riolet');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('BWLFES44M80C407K','Quattroporte');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('CISNIA37X86R911F','MPV');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('CIZGWH45Q71V543Z','Elantra');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('CSLOLY28G46O506M','G');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('DBLGDH64L13N537B','Forenza');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('DJQLIS80B95H293O','Cougar');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('DPJSBJ29Z52F587B','DB9');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('DQBXBH84Q87T608G','E350');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('DTNHEY49U97A228M','Astro');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('DWZGPH36V95T072R','Grand Am');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('DXDGKX90W87Y932Z','Escalade ESV');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('DZETJN50Z07U534A','Stealth');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('EBOLCV84Q24N774C','Achieva');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('EHGLZS25F40M201I','Century');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('EHNKGS82J60Q385Z','Eclipse');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('EKOTEO03D79C695W','Camaro');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('ENEGRD73I87H140X','F250');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('ETXKVQ18D71H299N','Suburban 2500');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('EUFYNR16X90S631F','Concorde');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('EUJURP79S37H611F','960');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('EZLSOV40Y29F786I','Eclipse');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('FALDMA79A02E678K','Jetta');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('FEQZTT01K44U855V','Grand Prix');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('FILXNU71F40Y532I','Montero');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('GICCIN03P68N368D','Range Rover');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('GKALBL56A02C139J','Suburban 1500');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('GPWFZG35E01C104Y','Endeavor');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('GVTHTE67W76X522E','V40');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('GWSWCE20P38A006U','Silverado 2500');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('GZEHLR76D39C543A','Countach');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('HHATWT08D60D062Y','Stratus');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('HHBEPI57O65K856C','Villager');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('HKGSWS83V01P425N','Corolla');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('HVYDZC52N40G147U','Continental Flying Spur');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('HYGYDE43Y42E709K','Sentra');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('HZAVUY41G66L333X','Econoline E350');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('IDNEDA42K99Z105D','SL-Class');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('IDUATR61E69Y654E','Firefly');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('IGMUSX66C80A459K','V50');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('IKCAYP92R66W837J','Touareg');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('IVVAMK71D96D702P','Tribute');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('JERYSF73Y93B513L','Camaro');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('JHSBBG81L95Q613T','Sentra');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('JTGHVB47L45I393J','Frontier');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('JXJDGT67V10U184X','XC90');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('KGWCCR64N20M371K','Escalade');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('KMPGHY22U71K207Q','Rabbit');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('KNROCO54P56H810X','Celica');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('KWAQDB74C35Z586L','Ram Wagon B150');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('KYMCSM73C48N347N','G');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('LJZAEO13N20W224J','F250');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('LKJXSC71S73H779Q','RAV4');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('LOSEGH03R19H163D','Cabriolet');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('LPWMRY69X73W341C','Esprit');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('LRGQSJ30V92V352A','Milan');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('LSFPBQ10U09G931S','Sorento');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('LWHQLJ48J26E443F','Club Wagon');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('LZYVRC98C75I155R','3 Series');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('LZYZFZ86Q98M893U','Suburban 2500');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('MBIOWU23F78K866P','Capri');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('MLEWLJ14B56G997X','Sebring');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('MOTDTS40Z94X404B','Regal');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('MQBVSE69G24X064B','Highlander');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('MQOITN77R10W569M','Prelude');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('MQRHFW38P55L584M','Interceptor');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('MRFBHV75F19E331I','XC70');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('MRRQBD39M25T250G','Rio');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('MUOGXW35O40R079Q','GLI');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('MXZDCD63C48U147N','Grand Prix');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('NABPLF99T42E507S','Z3');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('NFSRGR11Y03N801M','E-Series');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('NJODBW91S86G879X','Durango');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('NNASML76Q64W590P','Continental');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('NUOJUU31A45U320R','Malibu');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('NWWLEM13X36Q264E','VUE');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('NZKDTB88N83Q628F','Cougar');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('OBCPNB47W37D727O','Jetta');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('OBSAYK46W87D210D','Sierra 2500');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('ODAOBR73F09Q200J','Carrera GT');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('OHIGNH41D64K664W','Skylark');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('OIMLAU06U16T552F','Yukon XL 1500');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('OJTTKQ18U59R405T','Galaxie');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('OJZQXD44V55I204E','Quattroporte');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('OMASMN29R87E201T','B-Series');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('OQMVMT12S91T266A','Countryman');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('OTGPQC58Z84Z320S','Truck Xtracab SR5');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('OZVRKR96U73F698M','Previa');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('PADBXY05D59J640O','California');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('PEPAOE07O92M683Z','Celica');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('PJQKOH05A29Q376V','Murano');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('PMZCJF65P13O955Y','LeSabre');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('PRNQQS94T77N371B','Roadmaster');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('PUFMAQ18Q60C969U','Cooper');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('PXHVMC72N67J929R','Expedition');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('QDVRDB36T13B101K','914');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('QEFFZC20W06U053I','Sentra');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('QLFGBG14D97K963Z','Grand Caravan');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('QNNWOP03R38H444V','Escort');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('QSWUSY71S05C168H','Chariot');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('QUIUTN54N72M832J','Hombre');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('QVPIMX18Y61Y433R','Skylark');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('QYDKBO24F43L414S','Mariner');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('RARJPS09X74W370I','riolet');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('RGFIXV77C92K763N','Grand Marquis');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('RNCVFW69M72H227R','900');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('RSKYMP19X99L356F','Discovery');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('RTXMLP84W56D464V','Escalade EXT');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('RWXAHS16Q69C607E','PT Cruiser');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('RZCUNR76K90W458Y','F430');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('SBAUEH59M12P739I','S80');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('SSNTET86V60Q854J','Dakota Club');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('SXELZL26N68M016F','SL-Class');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('SXQPPS30C79D088A','Sierra Hybrid');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('SXWOIG54G61C100S','Expedition');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('SYQFES47S49E221E','Civic');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('SZZVBR22L52C335O','Sierra 2500');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('THCWHR18P38J711N','Montero');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('TIXXUP92K11F878S','Sebring');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('TMKVSM45P14O544K','Cougar');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('TQSUQI56J51H936A','Durango');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('UKBQOD31X04K086S','Safari');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('UMOFLD97Z40G646N','Prelude');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('UNDOAO64D63B838T','Mustang');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('UYJRHK61I69Y043U','Durango');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('VAZJSE96H09D817P','C70');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('VBTUXJ91X58P755I','Mustang');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('VKYFKX89T44T765R','A8');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('VLSJLZ43W81V022X','Dakota');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('VMLJQW32P83W006M','RX-7');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('WGNCIN69D18K665W','200');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('WJYBEY36T30G643B','Avalanche 2500');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('WKNHLB74D76A966H','E-Series');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('WNKCWP89Q19P287B','Explorer');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('WNWRCY32P99H912J','XL-7');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('WRRDBK28N46Z291X','Milan');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('WTYTET78D52E919H','D350');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('WVAVTQ14K11G229F','Z3');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('WVJGKB82T57E302J','Aerostar');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('WYXPHW89A87V093V','Firebird');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('XCWSMO29K71N898E','XC70');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('XEVFED62P40M660T','F250');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('XGQUWL98A04N888V','FX');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('XHKOVB62I60E869Q','Continental');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('XHLZXY13O72S493P','Range Rover');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('XKMHVJ74R79E723T','STS');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('XLIDDU69T06C416N','Supra');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('XQKLOF03H62I351U','E350');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('XRWMMI72M55K352Q','Verano');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('XUAPTR00W41V274B','9-3');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('XYHWCZ08K73F696Z','Silhouette');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('YIWLON15J07F038U','Sierra 2500');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('YJDRRB60D96K164R','Breeze');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('YQZCAY08U06W201F','Crown Victoria');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('YVUCJJ70V84H642L','RX-7');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('YWMBEH67B00Q536D','Elise');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('ZIWMID76K98U160D','Vibe');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('ZNDGNP59J71T638V','2500');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('ZPGJZH98O47C759B','Malibu');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('ZQIEER25Z09Q808X','Aztek');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('ZVEYQD17M26N391D','Monterey');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('ACFGNQ30L49C290E','Loyale');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('WVAVTQ14K11G229F','Ipsum');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('MQRHFW38P55L584M','Civic');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('CIZGWH45Q71V543Z','LeSabre');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('OQMVMT12S91T266A','Explorer');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('MBIOWU23F78K866P','S80');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('SZZVBR22L52C335O','Cube');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('SSNTET86V60Q854J','Catera');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('MRRQBD39M25T250G','Tucson');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('KGWCCR64N20M371K','RL');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('QYDKBO24F43L414S','Ram 2500');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('NNASML76Q64W590P','G-Series G30');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('WGNCIN69D18K665W','Savana 1500');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('GWSWCE20P38A006U','350Z');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('XYHWCZ08K73F696Z','Eurovan');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('PMZCJF65P13O955Y','NSX');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('WRRDBK28N46Z291X','GS');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('TIXXUP92K11F878S','Voyager');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('DXDGKX90W87Y932Z','C-Class');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('UKBQOD31X04K086S','LX');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('FALDMA79A02E678K','Altima');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('QNNWOP03R38H444V','NSX');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('WYXPHW89A87V093V','Prelude');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('MLEWLJ14B56G997X','Crown Victoria');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('OHIGNH41D64K664W','X3');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('LOSEGH03R19H163D','300');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('XRWMMI72M55K352Q','Clubman');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('YWMBEH67B00Q536D','3 Series');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('HKGSWS83V01P425N','LTD');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('GWSWCE20P38A006U','Ram 2500');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('YVUCJJ70V84H642L','Exige');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('OJZQXD44V55I204E','Land Cruiser');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('DBLGDH64L13N537B','Firebird');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('KGWCCR64N20M371K','Trans Sport');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('PJQKOH05A29Q376V','CLK-Class');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('LWHQLJ48J26E443F','V50');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('ATOPPV18I18V056E','MR2');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('EUJURP79S37H611F','Econoline E350');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('YQZCAY08U06W201F','SL-Class');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('ZNDGNP59J71T638V','Esperante');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('JXJDGT67V10U184X','4Runner');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('CIZGWH45Q71V543Z','CX-9');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('WNWRCY32P99H912J','S80');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('THCWHR18P38J711N','G-Class');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('EHGLZS25F40M201I','Dynasty');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('MRRQBD39M25T250G','Sierra 1500');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('VMLJQW32P83W006M','Mirage');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('HKGSWS83V01P425N','Continental');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('YWMBEH67B00Q536D','EXP');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('PADBXY05D59J640O','Z4');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('OBSAYK46W87D210D','SLR McLaren');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('WYXPHW89A87V093V','RX Hybrid');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('VKYFKX89T44T765R','Achieva');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('SBAUEH59M12P739I','Continental');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('KYMCSM73C48N347N','Prelude');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('AVJMVS27Z20H763L','Spirit');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('NNASML76Q64W590P','Firebird');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('ZVEYQD17M26N391D','Pathfinder');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('MRFBHV75F19E331I','Suburban 2500');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('WKNHLB74D76A966H','Cayman');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('PADBXY05D59J640O','GTI');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('MUOGXW35O40R079Q','LR4');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('PEPAOE07O92M683Z','Sentra');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('KYMCSM73C48N347N','Impala');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('RARJPS09X74W370I','F150');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('MQOITN77R10W569M','A6');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('EHNKGS82J60Q385Z','9-3');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('EHNKGS82J60Q385Z','Town & Country');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('UKBQOD31X04K086S','MX-6');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('ACFGNQ30L49C290E','X5');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('HKGSWS83V01P425N','Monaro');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('JHSBBG81L95Q613T','Mustang');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('DTNHEY49U97A228M','Savana 1500');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('FILXNU71F40Y532I','IS-F');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('FEQZTT01K44U855V','Mountaineer');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('SZZVBR22L52C335O','Econoline E150');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('YIWLON15J07F038U','RDX');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('NZKDTB88N83Q628F','XK');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('OBSAYK46W87D210D','Discovery Series II');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('DZETJN50Z07U534A','XLR-V');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('VKYFKX89T44T765R','DTS');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('XRWMMI72M55K352Q','Brougham');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('MLEWLJ14B56G997X','Amigo');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('XLIDDU69T06C416N','Sentra');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('QSWUSY71S05C168H','B-Series Plus');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('WJYBEY36T30G643B','S10');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('WTYTET78D52E919H','Armada');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('QNNWOP03R38H444V','Riviera');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('KYMCSM73C48N347N','Outback');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('TMKVSM45P14O544K','Cutlass');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('IGMUSX66C80A459K','Suburban 1500');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('GKALBL56A02C139J','Ram');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('WTYTET78D52E919H','Sable');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('IDUATR61E69Y654E','Ram 1500');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('EKOTEO03D79C695W','Yukon');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('YWMBEH67B00Q536D','H1');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('KYMCSM73C48N347N','S2000');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('ZVEYQD17M26N391D','Cirrus');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('YVUCJJ70V84H642L','Paseo');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('LZYZFZ86Q98M893U','Mighty Max Macro');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('EBOLCV84Q24N774C','Diamante');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('OZVRKR96U73F698M','Mazda3');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('RZCUNR76K90W458Y','Focus');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('LSFPBQ10U09G931S','Land Cruiser');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('EHNKGS82J60Q385Z','tC');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('EUJURP79S37H611F','Pajero');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('LKJXSC71S73H779Q','xB');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('KWAQDB74C35Z586L','Accord Crosstour');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('GZEHLR76D39C543A','Skylark');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('WRRDBK28N46Z291X','3500 Club Coupe');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('YQZCAY08U06W201F','Corvette');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('TIXXUP92K11F878S','Element');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('XCWSMO29K71N898E','Avenger');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('KYMCSM73C48N347N','Camaro');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('HHBEPI57O65K856C','90');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('ODAOBR73F09Q200J','Bravada');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('GPWFZG35E01C104Y','SC');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('PXHVMC72N67J929R','Bronco');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('CIZGWH45Q71V543Z','Cabriolet');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('EHNKGS82J60Q385Z','MPV');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('WNWRCY32P99H912J','Ram Van 3500');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('KWAQDB74C35Z586L','Focus');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('LWHQLJ48J26E443F','Alliance');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('RTXMLP84W56D464V','Celica');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('XHKOVB62I60E869Q','Suburban 2500');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('XKMHVJ74R79E723T','Q5');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('AYYGFF86S30M223A','Camaro');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('LPWMRY69X73W341C','F350');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('MRRQBD39M25T250G','CL-Class');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('XLIDDU69T06C416N','Esteem');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('WNWRCY32P99H912J','Swift');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('SBAUEH59M12P739I','E-Series');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('PXHVMC72N67J929R','S80');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('LKJXSC71S73H779Q','Thunderbird');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('BWLFES44M80C407K','Prius');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('OJZQXD44V55I204E','Golf');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('WRRDBK28N46Z291X','Odyssey');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('CSLOLY28G46O506M','Grand Vitara');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('CSLOLY28G46O506M','Sportage');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('MBIOWU23F78K866P','Caravan');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('WJYBEY36T30G643B','LS');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('UKBQOD31X04K086S','Cougar');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('YQZCAY08U06W201F','S-Class');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('RWXAHS16Q69C607E','Aspire');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('WGNCIN69D18K665W','New Beetle');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('JXJDGT67V10U184X','SX4');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('VAZJSE96H09D817P','Legend');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('IDNEDA42K99Z105D','RL');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('AVJMVS27Z20H763L','F-Series Super Duty');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('VAZJSE96H09D817P','Seville');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('DZETJN50Z07U534A','Freestar');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('OJTTKQ18U59R405T','Lancer');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('NABPLF99T42E507S','Town Car');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('SYQFES47S49E221E','Econoline E250');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('WVJGKB82T57E302J','SLK-Class');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('SXWOIG54G61C100S','Ram');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('KMPGHY22U71K207Q','Liberty');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('XQKLOF03H62I351U','325');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('VMLJQW32P83W006M','SSR');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('EUJURP79S37H611F','Odyssey');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('XYHWCZ08K73F696Z','Camry');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('AVJMVS27Z20H763L','Grand Marquis');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('DQBXBH84Q87T608G','Colt Vista');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('GZEHLR76D39C543A','Cirrus');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('XHKOVB62I60E869Q','GTI');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('TIXXUP92K11F878S','Continental');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('MOTDTS40Z94X404B','Silverado');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('OJZQXD44V55I204E','Challenger');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('WRRDBK28N46Z291X','Titan');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('TQSUQI56J51H936A','Safari');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('UKBQOD31X04K086S','325');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('GPWFZG35E01C104Y','2500 Club Coupe');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('FALDMA79A02E678K','Forester');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('WNKCWP89Q19P287B','Passat');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('NFSRGR11Y03N801M','GT-R');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('MUOGXW35O40R079Q','SL-Class');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('FALDMA79A02E678K','Golf');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('VMLJQW32P83W006M','Silverado');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('HHBEPI57O65K856C','Nitro');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('RSKYMP19X99L356F','Sentra');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('PXHVMC72N67J929R','TSX');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('LSFPBQ10U09G931S','Starion');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('KGWCCR64N20M371K','Monte Carlo');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('UKBQOD31X04K086S','Expedition EL');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('AYYGFF86S30M223A','Civic Si');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('ZPGJZH98O47C759B','Regal');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('NZKDTB88N83Q628F','Yukon XL 2500');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('OBCPNB47W37D727O','3500 Club Coupe');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('DBLGDH64L13N537B','Camry Hybrid');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('HZAVUY41G66L333X','Town Car');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('ZPGJZH98O47C759B','968');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('PUFMAQ18Q60C969U','Ascender');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('EHGLZS25F40M201I','Thunderbird');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('VBTUXJ91X58P755I','190E');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('OBSAYK46W87D210D','Marauder');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('OBCPNB47W37D727O','Matrix');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('EUJURP79S37H611F','Highlander');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('LJZAEO13N20W224J','Mazda6');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('WJYBEY36T30G643B','Q');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('NWWLEM13X36Q264E','Diablo');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('VMLJQW32P83W006M','Sentra');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('ODAOBR73F09Q200J','XT');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('DXDGKX90W87Y932Z','Cayenne');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('PXHVMC72N67J929R','928');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('GPWFZG35E01C104Y','Golf III');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('PJQKOH05A29Q376V','Axiom');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('BGQMOS11P86Q149K','L300');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('ZQIEER25Z09Q808X','CTS');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('RWXAHS16Q69C607E','Silhouette');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('FALDMA79A02E678K','Milan');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('NUOJUU31A45U320R','Exige');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('FEQZTT01K44U855V','GT350');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('QNNWOP03R38H444V','Spider');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('UNDOAO64D63B838T','Lumina');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('ZIWMID76K98U160D','Protege');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('JXJDGT67V10U184X','Echo');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('LPWMRY69X73W341C','Breeze');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('WYXPHW89A87V093V','1500');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('XUAPTR00W41V274B','IS');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('THCWHR18P38J711N','Savana 3500');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('NZKDTB88N83Q628F','300');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('XKMHVJ74R79E723T','Sonoma Club Coupe');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('MUOGXW35O40R079Q','Accord');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('UYJRHK61I69Y043U','Vandura 1500');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('KGWCCR64N20M371K','Ram Wagon B350');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('RWXAHS16Q69C607E','Mountaineer');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('ETXKVQ18D71H299N','Ranger');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('EKOTEO03D79C695W','Mustang');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('MUOGXW35O40R079Q','CR-V');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('LOSEGH03R19H163D','Galant');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('XGQUWL98A04N888V','F250');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('WNWRCY32P99H912J','M-Class');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('QEFFZC20W06U053I','PT Cruiser');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('SBAUEH59M12P739I','X-90');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('THCWHR18P38J711N','Mazda5');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('EUJURP79S37H611F','Achieva');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('OMASMN29R87E201T','Intrepid');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('MQOITN77R10W569M','Achieva');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('OJTTKQ18U59R405T','G-Series G10');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('DTNHEY49U97A228M','TL');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('MXZDCD63C48U147N','S-Series');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('ACFGNQ30L49C290E','Grand Marquis');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('DZETJN50Z07U534A','Sierra 3500');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('IKCAYP92R66W837J','Outback');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('MUOGXW35O40R079Q','Caliber');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('XEVFED62P40M660T','Premier');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('XLIDDU69T06C416N','Cavalier');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('CSLOLY28G46O506M','Ciera');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('EHGLZS25F40M201I','1500');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('JHSBBG81L95Q613T','Chariot');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('DTNHEY49U97A228M','E-Class');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('YJDRRB60D96K164R','Avalon');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('SXELZL26N68M016F','Voyager');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('ZNDGNP59J71T638V','7 Series');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('CSLOLY28G46O506M','F150');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('OJTTKQ18U59R405T','Bravada');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('PRNQQS94T77N371B','V40');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('PMZCJF65P13O955Y','Magnum');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('JXJDGT67V10U184X','New Yorker');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('RNCVFW69M72H227R','164');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('MLEWLJ14B56G997X','Avalanche');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('HVYDZC52N40G147U','Topaz');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('NWWLEM13X36Q264E','Town & Country');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('MOTDTS40Z94X404B','Millenia');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('SZZVBR22L52C335O','Legacy');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('ZIWMID76K98U160D','Suburban 1500');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('NWWLEM13X36Q264E','Virage');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('WTYTET78D52E919H','Pathfinder Armada');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('WVAVTQ14K11G229F','R32');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('TIXXUP92K11F878S','Safari');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('ETXKVQ18D71H299N','612 Scaglietti');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('BWLFES44M80C407K','9-7X');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('DQBXBH84Q87T608G','7 Series');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('OJZQXD44V55I204E','Legend');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('XLIDDU69T06C416N','Ranger');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('SZZVBR22L52C335O','Caprice');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('WTYTET78D52E919H','E-Class');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('XLIDDU69T06C416N','Viper');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('QUIUTN54N72M832J','Vantage');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('FALDMA79A02E678K','Civic');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('SXWOIG54G61C100S','Ranger');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('BWLFES44M80C407K','Mazda6');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('SYQFES47S49E221E','Tahoe');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('SSNTET86V60Q854J','Millenia');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('MQOITN77R10W569M','MPV');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('QUIUTN54N72M832J','Liberty');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('PXHVMC72N67J929R','E-350 Super Duty');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('QVPIMX18Y61Y433R','Explorer');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('PRNQQS94T77N371B','F350');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('YWMBEH67B00Q536D','F250');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('OMASMN29R87E201T','Pajero');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('XHLZXY13O72S493P','GTI');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('XRWMMI72M55K352Q','Civic');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('WTYTET78D52E919H','Charger');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('WRRDBK28N46Z291X','Suburban 2500');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('WTYTET78D52E919H','Justy');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('HZAVUY41G66L333X','9-5');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('WVJGKB82T57E302J','LS');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('WTYTET78D52E919H','Truck');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('MQRHFW38P55L584M','Sonoma');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('OBCPNB47W37D727O','Diamante');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('OTGPQC58Z84Z320S','Corolla');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('LZYVRC98C75I155R','Sorento');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('RZCUNR76K90W458Y','Envoy');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('QYDKBO24F43L414S','SLK-Class');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('MQBVSE69G24X064B','Sable');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('UNDOAO64D63B838T','Previa');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('THCWHR18P38J711N','LS');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('WNWRCY32P99H912J','RDX');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('HVYDZC52N40G147U','CX-7');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('EUFYNR16X90S631F','Fiero');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('PMZCJF65P13O955Y','Karif');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('UYJRHK61I69Y043U','Mountaineer');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('ZIWMID76K98U160D','Cooper');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('WTYTET78D52E919H','Windstar');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('QVPIMX18Y61Y433R','3 Series');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('BGQMOS11P86Q149K','Mazda2');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('BTLCNU38B77A480P','Savana 2500');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('MUOGXW35O40R079Q','Grand Voyager');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('FEQZTT01K44U855V','Flex');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('QUIUTN54N72M832J','RL');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('NJODBW91S86G879X','Mark VIII');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('LWHQLJ48J26E443F','G5');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('IDUATR61E69Y654E','Mountaineer');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('EHGLZS25F40M201I','Tracer');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('DQBXBH84Q87T608G','Eurovan');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('LPWMRY69X73W341C','QX56');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('RGFIXV77C92K763N','Versa');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('MQOITN77R10W569M','LX');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('LPWMRY69X73W341C','Thunderbird');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('HZAVUY41G66L333X','Legend');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('BGQMOS11P86Q149K','Mustang');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('WJYBEY36T30G643B','M3');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('JXJDGT67V10U184X','Dakota');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('OJTTKQ18U59R405T','Yukon');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('FEQZTT01K44U855V','Navigator L');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('SBAUEH59M12P739I','Montero');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('XHLZXY13O72S493P','E-Series');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('TQSUQI56J51H936A','Fortwo');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('GKALBL56A02C139J','Pilot');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('EUJURP79S37H611F','1000');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('LKJXSC71S73H779Q','Jetta');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('IDUATR61E69Y654E','Aviator');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('WNWRCY32P99H912J','Wrangler');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('OMASMN29R87E201T','Prius');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('AVJMVS27Z20H763L','MDX');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('WJYBEY36T30G643B','LeSabre');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('LSFPBQ10U09G931S','Rodeo');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('XHKOVB62I60E869Q','Sable');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('UYJRHK61I69Y043U','CL');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('AYYGFF86S30M223A','Corvette');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('PADBXY05D59J640O','Prius');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('HVYDZC52N40G147U','Z3');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('MRRQBD39M25T250G','Aries');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('HHBEPI57O65K856C','Intrepid');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('LKJXSC71S73H779Q','Camry');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('PMZCJF65P13O955Y','Avalon');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('QVPIMX18Y61Y433R','911');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('SXELZL26N68M016F','Civic Si');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('QYDKBO24F43L414S','LS');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('YWMBEH67B00Q536D','Trans Sport');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('BWLFES44M80C407K','Torrent');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('LRGQSJ30V92V352A','E-Series');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('SSNTET86V60Q854J','Q7');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('WGNCIN69D18K665W','XLR');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('HZAVUY41G66L333X','GTI');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('PADBXY05D59J640O','Blazer');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('SXELZL26N68M016F','V70');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('WGNCIN69D18K665W','V8 Vantage');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('DBLGDH64L13N537B','2500');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('NABPLF99T42E507S','9-3');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('HVYDZC52N40G147U','PT Cruiser');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('WNWRCY32P99H912J','L-Series');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('IGMUSX66C80A459K','Passport');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('FALDMA79A02E678K','Monte Carlo');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('OJTTKQ18U59R405T','Astro');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('THCWHR18P38J711N','Wrangler');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('BGQMOS11P86Q149K','Skyhawk');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('QNNWOP03R38H444V','Galant');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('XHKOVB62I60E869Q','Escort');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('OTGPQC58Z84Z320S','Dakota');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('OHIGNH41D64K664W','Grand Caravan');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('JERYSF73Y93B513L','Tredia');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('KYMCSM73C48N347N','Starion');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('HVYDZC52N40G147U','Frontier');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('GKALBL56A02C139J','New Beetle');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('JTGHVB47L45I393J','Diablo');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('NABPLF99T42E507S','SLX');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('ZVEYQD17M26N391D','Pilot');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('GZEHLR76D39C543A','Ram 1500 Club');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('WVAVTQ14K11G229F','Insight');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('EBOLCV84Q24N774C','Sable');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('QSWUSY71S05C168H','Grand Vitara');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('MRFBHV75F19E331I','Range Rover');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('MBIOWU23F78K866P','Lynx');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('SYQFES47S49E221E','Classic');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('JHSBBG81L95Q613T','S-Class');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('QYDKBO24F43L414S','Continental');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('DBLGDH64L13N537B','Tiburon');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('QLFGBG14D97K963Z','Diamante');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('RZCUNR76K90W458Y','W126');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('RTXMLP84W56D464V','Passat');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('UNDOAO64D63B838T','Elise');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('QDVRDB36T13B101K','V40');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('PUFMAQ18Q60C969U','CLK-Class');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('JXJDGT67V10U184X','Cougar');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('XHKOVB62I60E869Q','Vega');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('QSWUSY71S05C168H','Q');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('QSWUSY71S05C168H','Savana 1500');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('HHBEPI57O65K856C','A8');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('OTGPQC58Z84Z320S','57');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('IKCAYP92R66W837J','Crossfire');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('RARJPS09X74W370I','Fox');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('GWSWCE20P38A006U','Mazdaspeed 3');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('ZIWMID76K98U160D','Sierra');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('QUIUTN54N72M832J','Tribeca');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('YJDRRB60D96K164R','xA');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('GWSWCE20P38A006U','Blazer');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('DJQLIS80B95H293O','Diablo');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('OHIGNH41D64K664W','Montero Sport');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('GZEHLR76D39C543A','Land Cruiser');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('FEQZTT01K44U855V','Mirage');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('XLIDDU69T06C416N','Equus');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('JTGHVB47L45I393J','Esteem');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('TQSUQI56J51H936A','Explorer');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('VLSJLZ43W81V022X','Safari');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('PJQKOH05A29Q376V','SX4');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('JHSBBG81L95Q613T','Camry');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('MOTDTS40Z94X404B','Passat');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('QNNWOP03R38H444V','Grand Voyager');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('KGWCCR64N20M371K','Corvette');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('ETXKVQ18D71H299N','Lancer');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('THCWHR18P38J711N','ES');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('SXWOIG54G61C100S','Savana Cargo Van');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('PMZCJF65P13O955Y','GT');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('HYGYDE43Y42E709K','Tahoe');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('LKJXSC71S73H779Q','Skylark');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('WVJGKB82T57E302J','Legend');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('XYHWCZ08K73F696Z','Mark LT');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('OJZQXD44V55I204E','Escape');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('EUJURP79S37H611F','M5');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('XYHWCZ08K73F696Z','RAV4');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('GPWFZG35E01C104Y','Bronco');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('OJTTKQ18U59R405T','R-Class');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('GKALBL56A02C139J','F250');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('XLIDDU69T06C416N','Familia');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('RZCUNR76K90W458Y','C70');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('QEFFZC20W06U053I','S40');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('NUOJUU31A45U320R','Discovery');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('VAZJSE96H09D817P','D250 Club');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('RARJPS09X74W370I','Intrepid');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('VMLJQW32P83W006M','2500 Club Coupe');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('TIXXUP92K11F878S','Malibu');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('LSFPBQ10U09G931S','Golf');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('EUFYNR16X90S631F','GS');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('OTGPQC58Z84Z320S','Forte');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('QVPIMX18Y61Y433R','Silverado');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('EBOLCV84Q24N774C','E-Series');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('NZKDTB88N83Q628F','Ram 1500');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('ACFGNQ30L49C290E','Outback');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('UNDOAO64D63B838T','Navigator');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('XLIDDU69T06C416N','Rio');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('NUOJUU31A45U320R','S4');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('AVJMVS27Z20H763L','Sierra 2500');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('JXJDGT67V10U184X','Land Cruiser');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('NJODBW91S86G879X','Corvette');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('NFSRGR11Y03N801M','S80');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('BTLCNU38B77A480P','Mirage');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('OIMLAU06U16T552F','Suburban 1500');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('XEVFED62P40M660T','Dakota');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('RARJPS09X74W370I','SL-Class');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('GZEHLR76D39C543A','GT500');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('PEPAOE07O92M683Z','Grand Prix');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('XEVFED62P40M660T','Defender');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('KGWCCR64N20M371K','Neon');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('VAZJSE96H09D817P','Celica');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('HKGSWS83V01P425N','QX');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('KYMCSM73C48N347N','Rogue');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('NNASML76Q64W590P','Dakota');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('LJZAEO13N20W224J','6 Series');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('IVVAMK71D96D702P','Altima');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('YWMBEH67B00Q536D','Continental GTC');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('WJYBEY36T30G643B','Suburban 1500');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('EKOTEO03D79C695W','Matrix');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('XQKLOF03H62I351U','Transit Connect');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('HZAVUY41G66L333X','Prizm');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('KMPGHY22U71K207Q','Park Avenue');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('MUOGXW35O40R079Q','Express 2500');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('HHBEPI57O65K856C','RX Hybrid');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('VAZJSE96H09D817P','4Runner');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('FEQZTT01K44U855V','Golf');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('ATOPPV18I18V056E','Sienna');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('MXZDCD63C48U147N','Grand Marquis');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('NJODBW91S86G879X','F150');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('OMASMN29R87E201T','Grand Prix');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('PADBXY05D59J640O','1 Series');
INSERT INTO Abituale_Brand_Preferito_T(B_A_Codice_Fiscale,Brand_Preferito) VALUES ('LKJXSC71S73H779Q','Astro');
